CREATE TABLE IF NOT EXISTS "order_table" (
  "order_id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "product_id" BIGINT,
  "quantity" INTEGER NOT NULL,
  "version" BIGINT DEFAULT 0 NOT NULL,
  CONSTRAINT pk_order_table PRIMARY KEY (order_id)
);