type: object
description: Represents a product
title: ProductCreatePayload
properties:
  name:
    type: string
    nullable: false
    minLength: 10
    maxLength: 100
    description: The name of the product
  price:
    type: integer
    format: int32
    nullable: false
    minimum: 1
    maximum: 100
    description: The price of the product
  users:
    type: array
    nullable: false
    items:
      $ref: './userInput.yaml'
  uuid:
    type: string
    format: uuid
    nullable: false
    description: The unique identifier for the product
  releaseDate:
    type: string
    format: date
    description: The release date of the product
  details:
    type: array
    uniqueItems: false
    items:
      $ref: './productDetailsPayload.yaml'
  status:
    type: string
    enum:
      - ACTIVE
      - INACTIVE
    description: The status of the product
required:
  - name
  - price
  - users
  - uuid
