type: object
description: Represents a product
title: ProductPayload
properties:
  id:
    type: integer
    format: int64
    description: The unique identifier for the product
  name:
    type: string
    nullable: false
    maxLength: 10000
    description: The name of the product
  price:
    type: string
    nullable: false
    description: The price of the product
  users:
    type: array
    items:
      $ref: './userPayload.yaml'
  uuid:
    type: string
    format: uuid
    nullable: false
    description: The unique identifier for the product
  birthDate:
    type: string
    format: date
    description: The date and time the product was created
  status:
    type: string
    enum:
      - ACTIVE
      - INACTIVE
    description: The status of the product
